### ISSUE TITLE
Article cant get updated with Weclapp

### ISSUE THREAD

**Issue by boomix-dev** [hlohaus/SheProductNumber#1]
Hello,
im using Weclapp (external tool). And i tried to import the Articles from Weclapp into Shopware 5.
Weclapp has a integrated Shopware sync tool, that uses the Shopware API.

In Weclapp some Articles have a (+ plus) special character, in the Article number.
Something Like: "AB-001+".

When i install your Plugin, new Articles get imported with the special char. But old Articles with special characters cant get updated. I need to delete all Articles with special Characters and re-import them. Without your Plugin, i cant import new Articles. So your Plugin only work for creating new Articles with the Shopware API, or something like that.

I cant find any Detailed log in Weclapp.
The only error i get for every Article with special Character is:
"Generic Failure - HTTP/1.1 400 Bad Request"

Is there something i can do, or something that need to be changed in the Plugin ?

## Environment

Shopware 5.6.1
PHP 7.3
Weclapp (external tool)

## Steps to reproduce

1. Weclapp to Shopware Article Sync
2. New Articles get imported into shopware
3. Old Articles cant get Updated.

## Checklist

- [ X] I have checked [all issues](https://github.com/hlohaus/SheProductNumber/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ X] I am using the latest stable version of this plugin.

**Comment by hlohaus** [comment]
issue with 5.6 should be fixed
